// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQqvgbA8NHHSlP35xFgWAx_S57udvbGK0',
    appId: '1:754158823469:web:3c09db983aef2d1eb9b0a4',
    messagingSenderId: '754158823469',
    projectId: 'shopapp1234',
    authDomain: 'shopapp1234.firebaseapp.com',
    storageBucket: 'shopapp1234.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqWCheMgaquGf7K0IRtU6ObHfyxVtpxoM',
    appId: '1:754158823469:android:0dba6013a2a46ff9b9b0a4',
    messagingSenderId: '754158823469',
    projectId: 'shopapp1234',
    storageBucket: 'shopapp1234.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_-FuuqxQFlKrNBo9oesWu2yaPfk9tA9s',
    appId: '1:754158823469:ios:d3e4768edbec6d99b9b0a4',
    messagingSenderId: '754158823469',
    projectId: 'shopapp1234',
    storageBucket: 'shopapp1234.appspot.com',
    iosClientId: '754158823469-01bb9su7885mnh4nn7rs3v3ent1ssda9.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_-FuuqxQFlKrNBo9oesWu2yaPfk9tA9s',
    appId: '1:754158823469:ios:d3e4768edbec6d99b9b0a4',
    messagingSenderId: '754158823469',
    projectId: 'shopapp1234',
    storageBucket: 'shopapp1234.appspot.com',
    iosClientId: '754158823469-01bb9su7885mnh4nn7rs3v3ent1ssda9.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopapp',
  );
}
